version: '3.8'

services:
  postgres-sertaoComp:
    image: bitnami/postgresql:latest
    ports:
      - '5456:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - 'sertaoComp_pg_data:/bitnami/postgresql'

volumes:
  sertaoComp_pg_data: